# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
# pylint: skip-file
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from services.gprc_coms import branch_pb2


class branchEventSenderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MsgDelivery = channel.unary_unary(
                '/branchEventSender/MsgDelivery',
                request_serializer=branch_pb2.branchEventRequest.SerializeToString,  # pylint: disable=no-member
                response_deserializer=branch_pb2.branchEventResponse.FromString,  # pylint: disable=no-member
                )


class branchEventSenderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def MsgDelivery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_branchEventSenderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MsgDelivery': grpc.unary_unary_rpc_method_handler(
                    servicer.MsgDelivery,
                    request_deserializer=branch_pb2.branchEventRequest.FromString,   # pylint: disable=no-member
                    response_serializer=branch_pb2.branchEventResponse.SerializeToString,  # pylint: disable=no-member
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'branchEventSender', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class branchEventSender(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MsgDelivery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/branchEventSender/MsgDelivery',
            branch_pb2.branchEventRequest.SerializeToString, # pylint: disable=no-member
            branch_pb2.branchEventResponse.FromString, # pylint: disable=no-member
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
